config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root to: 'tasks#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
  end
  def index
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

   def create
  @task = Task.new(task_params)
end

private
def task_params
  params.require(:task).permit(:newtask)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<%= form_with scope: :task, local: true do |form| %>
<body bgcolor ="pink">
<h1 align="center">TODO LIST </h1>
            <p>

<h3 align ="center"><%= form.label :NEWTASK%><br>

               <%= form.text_area :newtask %></h3>
               </p>

<h2 align="center">Incomplete Task</h2>
<div class ="tasks" id = "incomplete_task">
</div>

<h2 align ="center">Complete Task</h2>
<div class ="tasks" id = "complete_task">
</div>

<p>
<%= form.submit %>

    </p>
</body>
<%end%>

app/views/tasks/new.html.erb
<%= form_with scope: :task, url: tasks_path, local: true do |form| %>
<%end %>

app/views/tasks/show.html.erb
<p>
  <strong>newtask:</strong>
  <%= @task.title %>
</p>